latest version sidekiq fixes forpapyrus
entdec/papyrus pull request #18
Opened 2023-08-01 05:43 UTC by rparse

2023-08-01 12:45 UTC, shubhrathasetty approved these changes

2023-08-08 10:40 UTC, plummip requested changes
- When importing inventory adjust we supose to be running a consolidation spool job. infortunately this is not happening anymore 
- If possible change the Papyrus::FormatParams to a class method
`Papyrus::ObjectConverter.serialize(someobj)`

2023-08-08 14:20 UTC, rparse commented
> * When importing inventory adjust we supose to be running a consolidation spool job. infortunately this is not happening anymore
> * If possible change the Papyrus::FormatParams to a class method
>   `Papyrus::ObjectConverter.serialize(someobj)`

Thank you for review!
Fixed second one, I guess first one its already fixed in import by you!

2023-08-09 10:35 UTC, plummip approved these changes

2023-08-09 10:36 UTC, merged