3765 - Reduce loop and added error handling
entdec/papyrus pull request #30
Opened 2024-02-12 11:50 UTC by rparse

https://github.com/boxture/oms/issues/3765

Reduce computers API call of computers and taken it from printers call only, as we don't care about computers without printers and handled API error .

2024-02-12 12:43 UTC, shubhrathasetty approved these changes

2024-02-13 11:04 UTC, tdegrunt requested changes
Just don't do the /printers call, other than that it's fine.

2024-02-13 11:05 UTC, plummip approved these changes

2024-02-13 11:59 UTC, rparse commented on app/jobs/papyrus/update_print_node_information_job.rb
> +      raise Papyrus::UpdatePrintNodeInformationException, 'API Error' if Papyrus.print_client.get('/printers').code != '200'
Thank you for review, modified the code as per your suggestion! Please check.

2024-02-13 12:08 UTC, plummip approved these changes

2024-02-13 12:18 UTC, tdegrunt approved these changes

2024-02-15 11:21 UTC, merged